# General options.
#
Options:
  activation_radius: 6
  # Use this option to change all the blocks behind the GUI every time the GUI is loaded.
  replace_blocks:
    enabled: true
    material: STONE
  # Every time the GUI is loaded it will remove every block that is in the screen (E.g. in case the player pushes a block with a piston)
  remove_screen_blocks: true
  # Enables the dynamic placing. If you disable it, the plugin will only place the GUIs and they'll stay permanently.
  dynamicPlacing:
    enabled: false
    # Delets all the GUIs from the islands in case you switch between non dynamic and dynamic placement.
    force_delete: true
    # Modes available:
    # 1 = onIsland (Only summons the GUI if there's any member on the island (Ignoring visitors))
    # 2 = onIslandOwner (Only if the owner of the island is on the island)
    # 3 = onOnline (Places the GUI if a member of the island is online)
    mode: 2


# All the schematics that you will palce GUIs in.

schematics:
  - "normal"
  - "desert"

# Information on the GUIs attributes and relative position
#
# Modify this values manually or with the command /setguilocation <Layout> (command recommended)

GUIs:
  # Schematic name
  normal:
    # Type of world in which the GUI settings will apply.
    overworld:
      # Place GUI? If its set to false no GUI will be placed.
      enabled: false
      # Offset of the GUI from the center of the island.
      # Recommended to use the command /setguilocation <Layout>
      offset:
        x: 12
        y: 3
        z: 3
      # Orientation of the GUI. (Also recommended to use the command)
      facing: west
      # Layout that will be used.
      layout: "GUIoverworld"
      # height of the layout
      height: 3
      # width of the layout
      width: 5
    nether:
      enabled: false
      offset:
        x: 1
        y: 15
        z: 5
        facing: north
        layout: "GUInether"
        height: 3
        width: 2
    the_end:
      enabled: false
      offset:
        x: 1
        y: 13
        z: 3
      facing: south
      layout: "GUIend"
      height: 2
      width: 4
  # Example using other schematic.
  desert:
    overworld:
      enabled: false
      offset:
        x: 12
        y: 5
        z: 2
      facing: west
      layout: "desertGUIoverworld"
      height: 3
      width: 5
    nether:
      enabled: false
      offset:
        x: 10
        y: 5
        z: 23
      facing: north
      layout: "desertGUInether"
      height: 3
      width: 2
    the_end:
      enabled: false
      offset:
        x: 3
        y: 6
        z: 23
      facing: south
      layout: "desertGUIend"
      height: 2
      width: 4