name: SkyblockAGUI
version: '${project.version}'
main: me.bounser.skyblockagui.SkyblockAGUI
api-version: 1.19
depend: [ AdvancedGUI, SuperiorSkyblock ]
authors: [ bounser ]
description: Give your skyblock islands GUIs!
commands:
  setguilocation:
  cancel: